sudo: required

services:
  - docker

before_install:
  - docker build -t kingrayhan/docker-react -f Dockerfile.dev .

scripts:
  - docker run -d kingrayhan/docker-react test -- --coverage

deploy:
  privider: "elasticbeanstalk"
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env-1"
  bucket_name: "elasticbeanstalk-us-east-2-253258169617"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_ID
  secret_access_key: $AWS_SECRET_KEY
