version: "3"

services:
  web:
    container_name: "web"
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/app
    ports:
      - 3000:3000
  test:
    container_name: "test"
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/app
    command: ["test", "--", "--coverage"]
