version: "3"

services:
  web:
    container_name: "web"
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/app
    ports:
      - 80:3000
  test:
    container_name: "test"
    buld:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/app
    ports:
      - 80:3000
    command: test
